# Agent Orchestrator - Coordinates query optimization workflow
# This module is the core controller. It ties together parsing, analysis,
# strategy application, and LLM evaluation.

from typing import Dict, List, Any, Optional
from dataclasses import dataclass
import sys

# Ensure this project is accessible via sys.path
sys.path.insert(0, '/home/galaxy/DB_setup/sql_optimizer_agent')

from analyzer.sql_parser import SQLParser, ParsedQuery
from analyzer.execution_plan import ExecutionPlanParser, ExecutionPlan
from analyzer.metadata import MetadataExtractor
from optimizer.bottleneck import BottleneckDetector, Bottleneck
from optimizer.strategies import OptimizationStrategies, OptimizationSuggestion
from optimizer.rewriter import QueryRewriter
from agent.llm_interface import LLMInterface
from agent.reflection_agent import ReflectionAgent
from validator.syntax_validator import SyntaxValidator
from validator.equivalence import EquivalenceValidator


@dataclass
class OptimizationResult:
    """Complete result of query optimization — the final payload returned to the caller."""
    original_query: str                          # The raw input query
    parsed_query: ParsedQuery                    # The structured parsed AST equivalent
    execution_plan: Optional[ExecutionPlan]      # The EXPLAIN ANALYZE result (if enabled)
    bottlenecks: List[Bottleneck]                # List of identified performance bottlenecks
    suggestions: List[OptimizationSuggestion]    # Formal list of optimization rule suggestions
    optimized_query: str                         # The final rebuilt SQL query
    llm_analysis: Optional[Dict[str, Any]]       # Output dictionary generated by the LLM
    expected_improvement: str                    # String estimate of performance gain
    validation_metadata: Dict[str, Any] = None  # Metadata about how the query was validated


class AgentOrchestrator:
    """Orchestrates the query optimization workflow by calling sub-modules in sequence."""

    def __init__(self, use_llm: bool = True, use_explain: bool = False):
        # Initialize internal state and modular components
        self.sql_parser = SQLParser()
        self.exec_plan_parser = ExecutionPlanParser()
        self.metadata_extractor = MetadataExtractor()
        self.bottleneck_detector = BottleneckDetector()
        self.strategies = OptimizationStrategies()
        self.rewriter = QueryRewriter()
        self.syntax_validator = SyntaxValidator()

        self.use_llm = use_llm
        self.use_explain = use_explain

        # Instantiate LLM interface only when needed to save resources
        if use_llm:
            self.llm = LLMInterface()
            self.reflection_agent = ReflectionAgent(self.llm, EquivalenceValidator())
        else:
            self.llm = None
            self.reflection_agent = None

    def optimize(self, query: str) -> OptimizationResult:
        """Run the complete optimization workflow in defined sequential steps."""

        # Step 1: Parse the query into a syntax tree and extract core components
        parsed_query = self.sql_parser.parse(query)

        # Step 2: Get execution plan (optional — runs actual EXPLAIN on the DB)
        execution_plan = None
        if self.use_explain:
            try:
                execution_plan = self.exec_plan_parser.get_execution_plan(query)
            except Exception as e:
                print(f"Warning: Could not get execution plan: {e}")

        # Step 3: Detect bottlenecks using rule-based metrics
        bottlenecks = self.bottleneck_detector.detect(query, parsed_query, execution_plan)

        # Step 4: Generate rule-based optimization suggestions
        suggestions = self.strategies.generate_suggestions(query, bottlenecks)

        # Step 5: LLM analysis (if enabled)
        llm_analysis = None
        if self.use_llm and self.llm:
            try:
                llm_analysis = self.llm.analyze_query(query, bottlenecks)
            except Exception as e:
                print(f"Warning: LLM analysis failed: {e}")

        # Step 6: Build the initial optimized query
        # Prefer the LLM-generated query when available
        if llm_analysis and 'optimized_query' in llm_analysis:
            optimized_query = llm_analysis['optimized_query']
        else:
            optimized_query = self.rewriter.create_optimized_query(
                query, suggestions, aggressive=True
            )

        # Step 6a: Reflection + refinement
        # FIX Bug 4: Never run the rewriter again after a successful reflection.
        # The old code always called rewriter.create_optimized_query() unconditionally
        # AFTER reflection, which corrupted the LLM-validated output every single time.
        # Now: rewriter only runs as a fallback when reflection itself crashes.
        if self.use_llm and self.reflection_agent:
            try:
                optimized_query = self.reflection_agent.reflect_and_refine(
                    query, optimized_query
                )
                # Reflection succeeded — do NOT rewrite again, skip to Step 6b
            except Exception as e:
                print(f"Warning: Reflection failed: {e}. Applying rule-based rewrite as fallback.")
                # Only rewrite when reflection itself failed
                optimized_query = self.rewriter.create_optimized_query(
                    optimized_query, suggestions, aggressive=True
                )
        else:
            # No LLM configured — rule-based rewrite is the only optimization step
            optimized_query = self.rewriter.create_optimized_query(
                optimized_query, suggestions, aggressive=True
            )

        # Step 6b: Syntax validation (only when use_explain=True and DB is live)
        if self.use_explain:
            validation = self.syntax_validator.validate(optimized_query)
            if not validation.is_valid:
                print(f"WARNING: Optimized query failed syntax validation: {validation.errors}")
                if llm_analysis and 'optimized_query' in llm_analysis:
                    # LLM query invalid — try pure rule-based fallback
                    fallback_query = self.rewriter.create_optimized_query(
                        query, suggestions, aggressive=True
                    )
                    fallback_validation = self.syntax_validator.validate(fallback_query)
                    if fallback_validation.is_valid:
                        optimized_query = fallback_query
                        print("INFO: Fell back to rule-based optimized query (passed validation).")
                    else:
                        optimized_query = query
                        print("WARNING: Fallback also failed validation. Returning original query.")
                else:
                    optimized_query = query
                    print("WARNING: Rule-based query failed validation. Returning original query.")

        # Step 6c: Inject validation method label into LLM explanation for the UI
        if llm_analysis:
            val_method = "Standard LIMIT Validation"
            if parsed_query.tables:
                from analyzer.schema_analyzer import SchemaAnalyzer
                from config import DB_CONFIG
                try:
                    schema_analyzer = SchemaAnalyzer(DB_CONFIG)
                    anchor_info = schema_analyzer.find_anchor_key(parsed_query.tables)
                    if anchor_info:
                        val_method = f"Dynamic Anchored Sampling (via {anchor_info['method']})"
                    else:
                        val_method = "Statistical TABLESAMPLE Validation (1% sampling)"
                except Exception:
                    val_method = "Statistical TABLESAMPLE Validation (1% sampling)"

            val_str = f"\n\n**Validation Method**: {val_method} securely evaluated on backend Live DB."
            if 'non_technical_summary' in llm_analysis:
                llm_analysis['non_technical_summary'] += val_str
            elif 'analysis' in llm_analysis:
                llm_analysis['analysis'] += val_str

        # Step 7: Estimate expected improvement
        expected_improvement = self._calculate_improvement(bottlenecks, suggestions, llm_analysis)

        return OptimizationResult(
            original_query=query,
            parsed_query=parsed_query,
            execution_plan=execution_plan,
            bottlenecks=bottlenecks,
            suggestions=suggestions,
            optimized_query=optimized_query,
            llm_analysis=llm_analysis,
            expected_improvement=expected_improvement
        )

    def _calculate_improvement(self, bottlenecks: List[Bottleneck],
                                suggestions: List[OptimizationSuggestion],
                                llm_analysis: Optional[Dict]) -> str:
        """Estimate the expected performance improvement as a human-readable string."""
        if llm_analysis and 'expected_speedup' in llm_analysis:
            return llm_analysis['expected_speedup']

        high_count   = len([b for b in bottlenecks if b.severity == 'HIGH'])
        medium_count = len([b for b in bottlenecks if b.severity == 'MEDIUM'])

        if high_count >= 2:
            return "Expected: 100x-1000x faster (minutes → seconds)"
        elif high_count == 1:
            return "Expected: 10x-100x faster"
        elif medium_count >= 2:
            return "Expected: 5x-10x faster"
        elif medium_count == 1:
            return "Expected: 2x-5x faster"
        else:
            return "Minor improvement expected"

    def get_line_by_line_report(self, result: OptimizationResult) -> List[Dict[str, Any]]:
        """Generate a line-by-line optimization report."""
        report = []

        for bottleneck in result.bottlenecks:
            entry = {
                'line':       bottleneck.line_number,
                'original':   bottleneck.line_content,
                'issue':      bottleneck.description,
                'severity':   bottleneck.severity,
                'impact':     bottleneck.impact,
                'suggestion': bottleneck.suggestion
            }
            for sugg in result.suggestions:
                if sugg.line_number == bottleneck.line_number:
                    entry['optimized']   = sugg.suggested_content
                    entry['explanation'] = sugg.explanation
                    break
            report.append(entry)

        if result.llm_analysis and 'suggestions' in result.llm_analysis:
            for llm_sugg in result.llm_analysis['suggestions']:
                line_num = llm_sugg.get('line_number', 0)
                if not any(r['line'] == line_num for r in report):
                    report.append({
                        'line':        line_num,
                        'original':    llm_sugg.get('original', ''),
                        'optimized':   llm_sugg.get('suggested', ''),
                        'issue':       'LLM detected issue',
                        'severity':    'MEDIUM',
                        'explanation': llm_sugg.get('explanation', ''),
                        'suggestion':  llm_sugg.get('estimated_improvement', '')
                    })

        report.sort(key=lambda x: x['line'])
        return report

    def close(self):
        """Clean up resources — terminate active database connection pools."""
        self.metadata_extractor.close()